# Generated by Django 6.0.3 on 2026-04-06 17:22

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('jobs', '0001_initial'),
        ('projects', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Isoscape',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('isoscape_path', models.CharField(max_length=1024)),
                ('uncertainty_path', models.CharField(max_length=1024)),
                ('mse', models.FloatField(blank=True, null=True)),
                ('r_squared', models.FloatField(blank=True, null=True)),
                ('selected_vars', models.JSONField(default=dict, help_text='{ threshold_vars, interp_vars, pred_vars } retornado pelo VSURF.')),
                ('model_type', models.CharField(choices=[('random_forest', 'Random Forest'), ('spatial_rf', 'Random Forest Espacial'), ('gradient_boosting', 'Gradient Boosting'), ('xgboost', 'XGBoost'), ('kriging_simple', 'Krigagem Simples'), ('kriging_universal', 'Krigagem Universal'), ('regression_kriging', 'Regression-Kriging')], default='random_forest', max_length=30)),
                ('uncertainty_method', models.CharField(choices=[('quantile_rf', 'Quantile RF'), ('bootstrap', 'Bootstrap')], default='quantile_rf', max_length=20)),
                ('is_public', models.BooleanField(default=False, help_text='Permite visualização sem autenticação.')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('job', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='isoscape', to='jobs.job')),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='isoscapes', to='projects.project')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
