# Generated by Django 6.0.3 on 2026-04-06 17:22

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('projects', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='StudyArea',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('file_path', models.CharField(max_length=1024)),
                ('crs', models.CharField(blank=True, help_text='Ex: EPSG:4674', max_length=50)),
                ('bbox', models.JSONField(blank=True, help_text='{ minx, miny, maxx, maxy }', null=True)),
                ('is_preset', models.BooleanField(default=False, help_text='True = shapefile pré-carregado pelo admin, disponível para todos.')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('project', models.ForeignKey(blank=True, help_text='Nulo quando for um shapefile pré-carregado pelo admin (preset).', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='study_areas', to='projects.project')),
            ],
            options={
                'ordering': ['name'],
            },
        ),
    ]
