# Generated by Django 6.0.3 on 2026-04-06 17:22

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('projects', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Job',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('pending', 'Pendente'), ('running', 'Em execução'), ('completed', 'Concluído'), ('failed', 'Falhou')], default='pending', max_length=20)),
                ('job_type', models.CharField(choices=[('gen_rasters', 'Geração de Rasters'), ('run_isoscape', 'Geração de Isoscape')], max_length=20)),
                ('celery_task_id', models.CharField(blank=True, max_length=255)),
                ('config', models.JSONField(default=dict, help_text='Parâmetros do job: modelo, incerteza, resolução, variáveis, colunas.')),
                ('log', models.TextField(blank=True, help_text='Log acumulado do processo R.')),
                ('progress_step', models.CharField(blank=True, help_text="Ex: '3/7 — Fitting Random Forest'", max_length=255)),
                ('error_message', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('finished_at', models.DateTimeField(blank=True, null=True)),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='jobs', to=settings.AUTH_USER_MODEL)),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='jobs', to='projects.project')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
