# Generated by Django 6.0.3 on 2026-04-06 17:22

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('shapefiles', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='RasterLayer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('variable', models.CharField(help_text='Ex: tavg, tmin, prec, bio1 … bio19', max_length=50)),
                ('resolution', models.CharField(choices=[('2.5', '2.5 arc-min'), ('5', '5 arc-min'), ('10', '10 arc-min')], max_length=5)),
                ('file_path', models.CharField(max_length=1024)),
                ('generated_at', models.DateTimeField(auto_now_add=True)),
                ('study_area', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='raster_layers', to='shapefiles.studyarea')),
            ],
            options={
                'ordering': ['variable'],
                'unique_together': {('study_area', 'variable', 'resolution')},
            },
        ),
    ]
